application:
{
	NSS = 256;
	CFL = 0.5;
	time = 10.0;
	nsteps = 50000;
	RES = 1.5;
	forcing = true;
	tauS = false;
	stats_every = 50;
	save_every = 10000;
	statfile = "./stats.csv";
	path = "./data";
	read:
	{
		U = "-";
		V = "-";
		W = "-";
	};
	write:
	{
		U = "./data/U_final.h5";
		V = "./data/V_final.h5";
		W = "./data/W_final.h5";
	};
	save_plane_every = 10;
	planefile = "./planes.bin";
};
